version: '2'
services:
  app:
    image: fidals/adarsha_pass_bot
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./../:/usr/src
    command: python main.py
